### ISSUE TITLE
关于 API

### ISSUE THREAD

**Issue by ruibaby** [PawNzZi/customizes-wehalo#1]
目前 Halo 的 Content api 还十分不完善，希望你们开发的时候有需要什么 api，可以到 Halo 提 issue。

https://api.halo.run/content-api.html

**Comment by PawNzZi** [comment]
了解！大佬！

**Comment by PawNzZi** [comment]
> 目前 Halo 的 Content api 还十分不完善，希望你们开发的时候有需要什么 api，可以到 Halo 提 issue。
> 
> https://api.halo.run/content-api.html
了解！大佬！

**Comment by qiaojia6** [comment]
大佬的教程点不开啦

**Comment by PawNzZi** [comment]
> 大佬的教程点不开啦

服务器到期啦，文章没有备份！

**Comment by qiaojia6** [comment]
好的，小白有点不太改的明白




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "PawNzZi"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 晚上6:23
收件人: "PawNzZi/customizes-wehalo"<customizes-wehalo@noreply.github.com&gt;; 
抄送: "993026881"<993026881@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PawNzZi/customizes-wehalo] 关于 API (#1)





  
大佬的教程点不开啦
  
服务器到期啦，文章没有备份！

**Comment by PawNzZi** [comment]
> 好的，小白有点不太改的明白
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人: "PawNzZi"<notifications@github.com&gt;; 
> 
> 发送时间: 2021年1月12日(星期二) 晚上6:23
> 
> 收件人: "PawNzZi/customizes-wehalo"<customizes-wehalo@noreply.github.com&gt;; 
> 
> 抄送: "993026881"<993026881@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
> 
> 主题: Re: [PawNzZi/customizes-wehalo] 关于 API (#1)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>   
> 
> 大佬的教程点不开啦
> 
>   
> 
> 服务器到期啦，文章没有备份！
> 
>  
> 
> —
> 
> You are receiving this because you commented.
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.

有群没？去群里问下！

**Comment by qiaojia6** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        大佬可以加个qq吗  有点问题想咨询一下
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                993026881
                            
                    
                        
                            
                                    993026881@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年1月12日 19:20，PawNzZi<notifications@github.com> 写道： 






好的，小白有点不太改的明白

------------------ 原始邮件 ------------------

发件人: "PawNzZi"<notifications@github.com>;

发送时间: 2021年1月12日(星期二) 晚上6:23

收件人: "PawNzZi/customizes-wehalo"<customizes-wehalo@noreply.github.com>;

抄送: "993026881"<993026881@qq.com>; "Comment"<comment@noreply.github.com>;

主题: Re: [PawNzZi/customizes-wehalo] 关于 API (#1)

大佬的教程点不开啦

服务器到期啦，文章没有备份！

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.



有群没？去群里问下！



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by qiaojia6** [comment]
代码好像不全写的功能不全 那些云函数的文件夹都是空的   跑起来以后没有样式
